<?php

return array(
    // 'Telegram' => 'Telegram',
    // 'Telegram bot username' => 'Nombre de usuario del bot de Telegram',
    // 'Telegram bot API key' => 'API key del bot de Telegram',
    // 'Chat id of private chat with bot' => 'Id del Chat privado con el bot',
    // 'Chat id of group chat with bot' => 'Id del Chat grupal con el bot',
    // 'Help on how to generate a bot' => 'Ayuda sobre cómo generar un bot',
    // 'Sent attachments along with notification' => '',
    // 'Telegram bot is not configured in Kanboard settings.' => '',
    // 'Go to ' => '',
    // 'Settings > Integrations > Telegram' => '',
    // ' and fill the form:' => '',
    // 'Telegram bot username: Username of your Telegram Bot' => '',
    // 'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => '',
    // 'Save Chat ID' => '',
    // 'Message %s not found!' => '',
    // 'Please send message %s ' => '',
    // 'Save chat id="%s" from "%s"?' => '',
    // 'To get your Telegram chat id,' => '',
    // '1. Send the message %s to' => '',
    // '2. Press' => '',
    // 'Get chat id' => '',
);

