<?php

return array(
    'Telegram' => 'Telegram',
    'Telegram bot username' => 'Telegram Bot Benutzername',
    'Telegram bot API key' => 'API Schlüssel für Telegram Bot',
    'Chat id of private chat with bot' => 'Chat ID für privaten Chat mit dem Bot',
    'Chat id of group chat with bot' => 'Chat ID für den Gruppen Chat mit dem Bot',
    'Help on how to generate a bot' => 'Hilfe für das Erzeugen eines Bots',
    // 'Sent attachments along with notification' => '',
    // 'Telegram bot is not configured in Kanboard settings.' => '',
    // 'Go to ' => '',
    // 'Settings > Integrations > Telegram' => '',
    // ' and fill the form:' => '',
    // 'Telegram bot username: Username of your Telegram Bot' => '',
    // 'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => '',
    // 'Save Chat ID' => '',
    // 'Message %s not found!' => '',
    // 'Please send message %s ' => '',
    // 'Save chat id="%s" from "%s"?' => '',
    // 'To get your Telegram chat id,' => '',
    // '1. Send the message %s to' => '',
    // '2. Press' => '',
    // 'Get chat id' => '',
);

