<?php

return array(
    'Telegram' => 'Telegram',
    'Telegram bot username' => 'Nome utente del bot di Telegram',
    'Telegram bot API key' => 'Chiave API del bot di Telegram',
    'Chat id of private chat with bot' => 'ID della chat privata con bot',
    'Chat id of group chat with bot' => 'ID della chat di gruppo con bot',
    'Help on how to generate a bot' => 'Aiuto su come generare un bot',
    'Sent attachments along with notification' => 'Invia allegati e notifica',
    'Telegram bot is not configured in Kanboard settings.' => 'Il bot di Telegram non è configurato nelle impostazioni di Kanboard.',
    'Go to ' => 'Vai a ',
    'Settings > Integrations > Telegram' => 'Impostazioni> Integrazioni> Telegram',
    ' and fill the form:' => ' e compila il modulo:',
    'Telegram bot username: Username of your Telegram Bot' => 'Nome utente del bot Telegram: nome utente del tuo Bot Telegram',
    'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => 'Chiave API del bot di Telegram: token API HTTP generato da BotFather dopo la creazione del bot',
    'Save Chat ID' => 'Salva l\'ID della chat',
    'Message %s not found!' => 'Messaggio %s non trovato!',
    'Please send message %s ' => 'Si prega di inviare il messaggio %s',
    'Save chat id="%s" from "%s"?' => 'Salva chat id = "%s" da "%s"?',
    'To get your Telegram chat id,' => 'Per ottenere il tuo chat ID Telegram,',
    '1. Send the message %s to' => '1. Invia il messaggio %s a',
    '2. Press' => '2. Premere',
    'Get chat id' => 'Ottieni l\'ID della chat',
);

