<?php

return array(
    'Telegram' => 'Telegram',
    'Telegram bot username' => 'Telegram bot felhasználónév',
    'Telegram bot API key' => 'Telegram bot API kulcs',
    'Chat id of private chat with bot' => 'A bottal történő személyes csevegés csevegés-azonosítója',
    'Chat id of group chat with bot' => 'A bottal történő csoportos csevegés csevegés-azonosítója',
    'Help on how to generate a bot' => 'Segítség egy bot előállításához',
    // 'Sent attachments along with notification' => '',
    // 'Telegram bot is not configured in Kanboard settings.' => '',
    // 'Go to ' => '',
    // 'Settings > Integrations > Telegram' => '',
    // ' and fill the form:' => '',
    // 'Telegram bot username: Username of your Telegram Bot' => '',
    // 'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => '',
    // 'Save Chat ID' => '',
    // 'Message %s not found!' => '',
    // 'Please send message %s ' => '',
    // 'Save chat id="%s" from "%s"?' => '',
    // 'To get your Telegram chat id,' => '',
    // '1. Send the message %s to' => '',
    // '2. Press' => '',
    // 'Get chat id' => '',
);

